# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RB61GI-g1W0k_CcZsKcGxP40T2kx-gdU
"""

pip install google-play-scraper

pip install pandas

!pip install nltk

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'gov.nc.dhhs.exposurenotification',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    
)

import json
import csv

#with open('G:/content/drive/MyDrive/appreviews.json') as json_file:
	#jsondata = json.load(json_file)

data_file = open('appReviews.csv', 'w', newline='')
csv_writer = csv.writer(data_file)

count = 0
for data in result:
	if count == 0:
		header = data.keys()
		csv_writer.writerow(header)
		count += 1
	csv_writer.writerow(data.values())

data_file.close()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
# %matplotlib inline
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls
import plotly.express as px

import pandas as pd
df = pd.read_csv('appReviews.csv')
df.head()

fig = px.histogram(df, x=  "score")
fig.update_traces(marker_color="turquoise",marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5)
fig.update_layout(title_text='score')
fig.show()

import nltk
from nltk.corpus import stopwords
# Create stopword list:
stopwords = set(STOPWORDS)
stopwords.update(["br", "href"])
textt = " ".join(review for review in df.Text)
wordcloud = WordCloud(stopwords=stopwords).generate(textt)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.savefig('wordcloud11.png')
plt.show()

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'gov.michigan.MiCovidExposure',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    
)

import json
import csv

#with open('G:/content/drive/MyDrive/appreviews.json') as json_file:
	#jsondata = json.load(json_file)

data_file = open('appReviews.csv', 'w', newline='')
csv_writer = csv.writer(data_file)

count = 0
for data in result:
	if count == 0:
		header = data.keys()
		csv_writer.writerow(header)
		count += 1
	csv_writer.writerow(data.values())

data_file.close()

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'gov.wi.covid19.exposurenotifications',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    
)

import json
import csv

#with open('G:/content/drive/MyDrive/appreviews.json') as json_file:
	#jsondata = json.load(json_file)

data_file = open('appReviews.csv', 'w', newline='')
csv_writer = csv.writer(data_file)

count = 0
for data in result:
	if count == 0:
		header = data.keys()
		csv_writer.writerow(header)
		count += 1
	csv_writer.writerow(data.values())

data_file.close()

print(result)

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'gov.wi.covid19.exposurenotifications',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    
)

print(result)

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'gov.ca.covid19.exposurenotifications',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    
)

print(result)

from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'gov.azdhs.covidwatch.android',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    
)

import json
import csv

#with open('G:/content/drive/MyDrive/appreviews.json') as json_file:
	#jsondata = json.load(json_file)

data_file = open('appReviews.csv', 'w', newline='')
csv_writer = csv.writer(data_file)

count = 0
for data in result:
	if count == 0:
		header = data.keys()
		csv_writer.writerow(header)
		count += 1
	csv_writer.writerow(data.values())

data_file.close()

from google.colab import drive
drive.mount('/content/drive')

import json
import csv

#with open('G:/content/drive/MyDrive/appreviews.json') as json_file:
	#jsondata = json.load(json_file)

data_file = open('appReviews.csv', 'w', newline='')
csv_writer = csv.writer(data_file)

count = 0
for data in result:
	if count == 0:
		header = data.keys()
		csv_writer.writerow(header)
		count += 1
	csv_writer.writerow(data.values())

data_file.close()